import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import LeftsideBar from "@/components/shared/Leftsidebar";
import "../globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
        >
          <Topbar />
          <main className="flex flex-row">
            <LeftsideBar  />
            <section className="main-container ">
              <div className="w-full max-w-4xl">

                {children}
              </div>

            </section>
            <RightSidebar />
          </main>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  );
}
